#helm install genesis -f values/noproxy-and-novault/genesis.yaml -n supplychain-bes besu-genesis
global:
  serviceAccountName: bevel-auth
  vault:
    type: kubernetes
  cluster:
    provider: kind
    cloudNativeServices: false
    
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    gasLimit: '0x1fffffffffffff' 
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
    contractSizeLimit: 2147483647
    londonBlock: 0
    zeroBaseFee: true
    maxFeePerGas: 0
    maxPriorityFeePerGas: 0
    gasUsed: "0x0"
  blockchain:
    nodes:
      generate: true
      count: 4
    accountPassword: 'password'
