---
#helm install member-1 -f values/noproxy-and-novault/txnode.yml -n supplychain-bes besu-node 
#helm upgrade member-1 -f values/noproxy-and-novault/txnode.yml -n supplychain-bes besu-node
global:
  serviceAccountName: bevel-auth
  cluster:
    provider: kind
    cloudNativeServices: false
  vault:
    type: kubernetes
  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local

storage:
  size: "2Gi"
  provisioner: rancher.io/local-path
  size: "1Gi"
  # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
  reclaimPolicy: "Delete" # choose from: Delete | Retain
  volumeBindingMode: WaitForFirstConsumer # choose from: Immediate | WaitForFirstConsumer
  allowedTopologies:
    enabled: false
tessera:
  enabled: false
  tessera:
    tlsMode: "OFF"
  resources:
    cpuLimit: 0.25
    cpuRequest: 0.05
    memLimit: "2G"
    memRequest: "1G"
    password: 'password'
  storage:
    enabled: false
    size: 1Gi
    dbSize: 2Gi
    allowedTopologies:
      enabled: false
  
tls:
  enabled: false
  settings:
    certSubject: CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB
    tmTls: true

node:
  removeKeysOnDelete: false # this will erase keys - so be careful with this on validators
  isBootnode: false    # set this to true if this node is a bootnode
  usesBootnodes: false
  besu:
    envBesuOpts: ""  
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 0.25
      cpuRequest: 0.05
      memLimit: "1G"
      memRequest: "300M"
    account:
      password: 'password'
